### ISSUE TITLE
Latest aiohttp(3.9 or higher) breaks the application

### ISSUE THREAD

**Issue by pangtg** [mvanderlee/aiotrino#4]
Latest aiohttp (as for now, 3.9.3) breaks aiotrino with the following error. Solution is to set the aiohttp version to 3.8, or update the trinoresponsehandler.set_response_params() function to accept unknown parameters (and possibally skip them)

Error received:
trinoresponsehandler.set_response_params() got an unexpected keyword argument 'timeout_ceil_threshold'

**Comment by mvanderlee** [comment]
Thank you for reporting @pangtg
I've 0.2.3 should fix the issue
